version: '2'
services:
  nginx:
    image: nginx:1.11.9
    depends_on:
      - practicalml
    ports:
      - "8000:8000"
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - static:/var/www/practicalml/static
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - NGINX_HOST=nginx
      - NGINX_PORT=8000

  practicalml:
    build: .
    depends_on:
      - redis
    volumes:
      - mldb:/usr/src/app/data
      - static:/var/www/practicalml/static

  redis:
    image: redis:3.2.6

volumes:
  mldb:
  static:
