# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candlestick',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('prediction', models.DecimalField(decimal_places=4, max_digits=20)),
                ('prediction_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together=set([('time', 'prediction_type')]),
        ),
    ]
